import re
import uuid

from fpdf import FPDF
from PIL import Image

from app import config
from app.schemas import Comic

_REPLACEMENTS = {
    "\u2018": "'",
    "\u2019": "'",
    "\u201c": '"',
    "\u201d": '"',
    "\u2013": "-",
    "\u2014": "-",
    "\u2026": "...",
    "\u2022": "-",
    "\u00a0": " ",
    "\u00e9": "e",
}


def _safe(text: str) -> str:
    cleaned = "".join(_REPLACEMENTS.get(ch, ch) for ch in str(text))
    return cleaned.encode("latin-1", "replace").decode("latin-1")


def _image_path(image_url: str | None):
    if not image_url:
        return None
    name = image_url.rstrip("/").split("/")[-1]
    name = re.sub(r"[^A-Za-z0-9_.-]", "", name)
    if not name:
        return None
    path = config.GENERATED_DIR / name
    return path if path.exists() else None


def build_pdf(comic: Comic) -> str:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(12, 12, 12)
    pdf.add_page()

    pdf.set_font("helvetica", "B", 24)
    pdf.multi_cell(0, 10, _safe(comic.title), align="C")
    pdf.ln(2)
    if comic.logline:
        pdf.set_font("helvetica", "I", 11)
        pdf.multi_cell(0, 6, _safe(comic.logline), align="C")
    pdf.ln(4)
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5, "Generated by ComicCraft - AI Comic Story Creator", align="C")
    pdf.set_text_color(0, 0, 0)

    page_width = pdf.w - pdf.l_margin - pdf.r_margin

    for index, panel in enumerate(comic.panels, start=1):
        needed = 70
        if pdf.get_y() + needed > pdf.h - 20:
            pdf.add_page()

        pdf.set_fill_color(245, 245, 245)
        pdf.set_font("helvetica", "B", 11)
        pdf.multi_cell(page_width, 7, f"Panel {index}", border=1, fill=True)

        path = _image_path(panel.image_url)
        if path:
            try:
                with Image.open(path) as im:
                    w, h = im.size
                max_w = page_width
                max_h = 110
                scale = min(max_w / w, max_h / h)
                draw_w, draw_h = w * scale, h * scale
                x = pdf.l_margin + (page_width - draw_w) / 2
                pdf.image(str(path), x=x, w=draw_w, h=draw_h)
                pdf.ln(3)
            except Exception:
                pass

        if panel.narration:
            pdf.set_font("helvetica", "B", 10)
            pdf.multi_cell(page_width, 5.5, f"Narration: {_safe(panel.narration)}")

        if panel.dialogues:
            pdf.set_font("helvetica", "", 10)
            for d in panel.dialogues:
                pdf.multi_cell(page_width, 5.5, f"{_safe(d.speaker)}: {_safe(d.line)}")

        pdf.ln(6)

    filename = f"comiccraft_{uuid.uuid4().hex[:10]}.pdf"
    out_path = config.DOWNLOADS_DIR / filename
    pdf.output(str(out_path))
    return str(out_path)